all:
	python ./plot_rdf.py ../data/poly_ACNCa/poly_ACNCa_rdf_Ca_O.csv ../data/poly_ACNMg/poly_ACNMg_rdf_Mg_O.csv ../data/poly_ACNCa/poly_ACNCa-1_rdf_Ca_O.csv ../data/poly_ACNMg/poly_ACNMg-1_rdf_Mg_O.csv \
	-n 'Ca-O(P) [Ca$$_2$$Zn$$_2$$P]' 'Mg-O(P) [Mg$$_2$$Zn$$_2$$P]' 'Ca-O(P) [CaZn$$_2$$P]' 'Mg-O(P) [MgZn$$_2$$P]' -l .5:6.2 -o ../FigureS1a.pdf
	# ...
	python ./plot_rdf.py ../data/poly_ACNCa/poly_ACNCa_rdf_Ca_ACN_N.csv ../data/poly_ACNMg/poly_ACNMg_rdf_Mg_ACN_N.csv ../data/poly_ACNCa/poly_ACNCa-1_rdf_Ca_ACN_N.csv ../data/poly_ACNMg/poly_ACNMg-1_rdf_Mg_ACN_N.csv \
	-n 'Ca-N(ACN) [Ca$$_2$$Zn$$_2$$P]' 'Mg-N(ACN) [Mg$$_2$$Zn$$_2$$P]' 'Ca-N(ACN) [CaZn$$_2$$P]' 'Mg-N(ACN) [MgZn$$_2$$P]' -l .5:5 -o ../FigureS1b.pdf
	# ...
	python ./plot_rdf.py ../data/poly_ACNCa/poly_ACNCa_rdf_Zn_Px_N.csv ../data/poly_ACNMg/poly_ACNMg_rdf_Zn_Px_N.csv ../data/poly_ACNCa/poly_ACNCa-1_rdf_Zn_Px_N.csv ../data/poly_ACNMg/poly_ACNMg-1_rdf_Zn_Px_N.csv ../data/poly_ACNCa/poly_ACNCa-2_rdf_Zn_Px_N.csv \
	-n 'Zn-N(P) [Ca$$_2$$Zn$$_2$$P]' 'Zn-N(P) [Mg$$_2$$Zn$$_2$$P]' 'Zn-N(P) [CaZn$$_2$$P]' 'Zn-N(P) [MgZn$$_2$$P]' 'Zn-N(P) [Zn$$_2$$P]' -l .5:4 -o ../FigureS2a.pdf
	# ...
	python ./plot_rdf.py ../data/poly_ACNCa/poly_ACNCa_rdf_Zn_O.csv ../data/poly_ACNMg/poly_ACNMg_rdf_Zn_O.csv ../data/poly_ACNCa/poly_ACNCa-1_rdf_Zn_O.csv ../data/poly_ACNMg/poly_ACNMg-1_rdf_Zn_O.csv ../data/poly_ACNCa/poly_ACNCa-2_rdf_Zn_O.csv \
	-n 'Zn-O(P) [Ca$$_2$$Zn$$_2$$P]' 'Zn-O(P) [Mg$$_2$$Zn$$_2$$P]' 'Zn-O(P) [CaZn$$_2$$P]' 'Zn-O(P) [MgZn$$_2$$P]' 'Zn-O(P) [Zn$$_2$$P]' -l .5:5.5 -o ../FigureS2b.pdf
	# ...
	python ./plot_da.py ../data/poly_ACNCa/poly_ACNCa_da.csv ../data/poly_ACNMg/poly_ACNMg_da.csv ../data/poly_ACNCa/poly_ACNCa-1_da.csv ../data/poly_ACNMg/poly_ACNMg-1_da.csv ../data/poly_ACNCa/poly_ACNCa-2_da.csv \
	-n 'Ca$$_2$$Zn$$_2$$P' 'Mg$$_2$$Zn$$_2$$P' 'CaZn$$_2$$P' 'MgZn$$_2$$P' 'Zn$$_2$$P' -c "v0xv1" -y "v0xv1 (°)" -o ../FigureS3a.pdf
	# ...
	python ./plot_da.py ../data/poly_ACNCa/poly_ACNCa_da.csv ../data/poly_ACNMg/poly_ACNMg_da.csv ../data/poly_ACNCa/poly_ACNCa-1_da.csv ../data/poly_ACNMg/poly_ACNMg-1_da.csv ../data/poly_ACNCa/poly_ACNCa-2_da.csv \
	-n 'Ca$$_2$$Zn$$_2$$P' 'Mg$$_2$$Zn$$_2$$P' 'CaZn$$_2$$P' 'MgZn$$_2$$P' 'Zn$$_2$$P' -c "v2xv3" -y "v2xv3 (°)" -o ../FigureS3b.pdf
	# ...
	python ./plot_da.py ../data/poly_ACNCa/poly_ACNCa_da.csv ../data/poly_ACNMg/poly_ACNMg_da.csv ../data/poly_ACNCa/poly_ACNCa-1_da.csv ../data/poly_ACNMg/poly_ACNMg-1_da.csv ../data/poly_ACNCa/poly_ACNCa-2_da.csv \
	-n 'Ca$$_2$$Zn$$_2$$P' 'Mg$$_2$$Zn$$_2$$P' 'CaZn$$_2$$P' 'MgZn$$_2$$P' 'Zn$$_2$$P' -c "v4xv6" -y "v4xv6 (°)" -o ../FigureS4a.pdf
	# ...
	python ./plot_da.py ../data/poly_ACNCa/poly_ACNCa_da.csv ../data/poly_ACNMg/poly_ACNMg_da.csv ../data/poly_ACNCa/poly_ACNCa-1_da.csv ../data/poly_ACNMg/poly_ACNMg-1_da.csv ../data/poly_ACNCa/poly_ACNCa-2_da.csv \
	-n 'Ca$$_2$$Zn$$_2$$P' 'Mg$$_2$$Zn$$_2$$P' 'CaZn$$_2$$P' 'MgZn$$_2$$P' 'Zn$$_2$$P' -c "v8xv10" -y "v8xv10 (°)" -o ../FigureS4b.pdf
